### ISSUE TITLE
graphite server not working currently

### ISSUE THREAD

**Issue by dbwest** [udacity/devops-intro-project#43]
The graphite server throws errors when I stand it up on Google Compute engine with the scripts.

**Comment by shubham1172** [comment]
Same! I am using AWS and nginx says "internal server error". There must be something wrong with the scripts. Dumping log snippet from packer script control_server.json:

```amazon-ebs: Collecting cairocffi (from graphite-web)[0m
[0;32m    amazon-ebs: Downloading https://files.pythonhosted.org/packages/85/89/1a6385420cd69bf2dde568946d9136ac3e549881618adff9ad9646f3df31/cairocffi-0.8.0.tar.gz (79kB)[0m
[0;32m    amazon-ebs: Complete output from command python setup.py egg_info:[0m
[0;32m    amazon-ebs: c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory[0m
[0;32m    amazon-ebs: compilation terminated.[0m
[0;32m    amazon-ebs: Traceback (most recent call last):[0m
[0;32m    amazon-ebs: File "<string>", line 1, in <module>[0m
[0;32m    amazon-ebs: File "/tmp/pip-build-ggJLPp/cairocffi/setup.py", line 44, in <module>[0m
[0;32m    amazon-ebs: extras_require={'xcb': ['xcffib>=0.3.2']},[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/distutils/core.py", line 111, in setup[0m
[0;32m    amazon-ebs: _setup_distribution = dist = klass(attrs)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__[0m
[0;32m    amazon-ebs: self.fetch_build_eggs(attrs['setup_requires'])[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs[0m
[0;32m    amazon-ebs: replace_conflicting=True,[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve[0m
[0;32m    amazon-ebs: dist = best[req.key] = env.best_match(req, ws, installer)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match[0m
[0;32m    amazon-ebs: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ggJLPp/cairocffi/[0m
[0;32m    amazon-ebs: return self.obtain(req, installer)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain[0m
[0;32m    amazon-ebs: return installer(requirement)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg[0m
[0;32m    amazon-ebs: return cmd.easy_install(req)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install[0m
[0;32m    amazon-ebs: return self.install_item(spec, dist.location, tmpdir, deps)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item[0m
[0;32m    amazon-ebs: dists = self.install_eggs(spec, download, tmpdir)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs[0m
[0;32m    amazon-ebs: return self.build_and_install(setup_script, setup_base)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install[0m
[0;32m    amazon-ebs: self.run_setup(setup_script, setup_base, args)[0m
[0;32m    amazon-ebs: File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup[0m
[0;32m    amazon-ebs: raise DistutilsError("Setup script exited with %s" % (v.args[0],))[0m
[0;32m    amazon-ebs: distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: ----------------------------------------[0m
[0;32m    amazon-ebs: You are using pip version 8.1.1, however version 10.0.1 is available.[0m
[0;32m    amazon-ebs: You should consider upgrading via the 'pip install --upgrade pip' command.[0m
[0;32m    amazon-ebs: cp: cannot stat 'examples/graphite.wsgi.example': No such file or directory[0m
[0;32m    amazon-ebs: cp: cannot stat '/opt/graphite/webapp/graphite/local_settings.py.example': No such file or directory[0m
[0;32m    amazon-ebs: python: can't open file '/opt/graphite/webapp/graphite/manage.py': [Errno 2] No such file or directory[0m
[0;32m    amazon-ebs: chown: cannot access '/opt/graphite/webapp/': No such file or directory[0m```

**Comment by vprocopan** [comment]
is it supposed to be url/graphite?

**Comment by 13rac1** [comment]
Here is the `pip` section of the Graphite install for the current version. There seems to be quite a few issues.
```
    virtualbox-iso: Downloading/unpacking https://github.com/graphite-project/ceres/tarball/master
    virtualbox-iso: Downloading master
    virtualbox-iso: Running setup.py (path:/tmp/pip-cd_oY3-build/setup.py) egg_info for package from https://github.com/graphite-project/ceres/tarball/master
    virtualbox-iso:
    virtualbox-iso: Installing collected packages: ceres
    virtualbox-iso: Running setup.py install for ceres
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-node-write from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/convert-wsp-to-ceres from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-tree-find from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-node-read from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-maintenance from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/slicecat from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-tree-create from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/ceres-node-create from 644 to 755
    virtualbox-iso:
    virtualbox-iso: changing mode of /usr/local/bin/ceres-node-write to 755
    virtualbox-iso: changing mode of /usr/local/bin/convert-wsp-to-ceres to 755
    virtualbox-iso: changing mode of /usr/local/bin/ceres-tree-find to 755
    virtualbox-iso: changing mode of /usr/local/bin/ceres-node-read to 755
    virtualbox-iso: changing mode of /usr/local/bin/ceres-maintenance to 755
    virtualbox-iso: changing mode of /usr/local/bin/slicecat to 755
    virtualbox-iso: changing mode of /usr/local/bin/ceres-tree-create to 755
    virtualbox-iso: changing mode of /usr/local/bin/ceres-node-create to 755
    virtualbox-iso: Successfully installed ceres
    virtualbox-iso: Cleaning up...
    virtualbox-iso: Downloading/unpacking whisper
    virtualbox-iso: Downloading whisper-1.1.5.tar.gz
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/whisper/setup.py) egg_info for package whisper
    virtualbox-iso:
    virtualbox-iso: Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from whisper)
    virtualbox-iso: Installing collected packages: whisper
    virtualbox-iso: Running setup.py install for whisper
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-dump.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/find-corrupt-whisper-files.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-fill.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-diff.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-update.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-create.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-fetch.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-set-aggregation-method.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-set-xfilesfactor.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/rrd2whisper.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-merge.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-resize.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-info.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-auto-resize.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/update-storage-times.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/whisper-auto-update.py from 644 to 755
    virtualbox-iso:
    virtualbox-iso: changing mode of /usr/local/bin/whisper-auto-resize.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-dump.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/find-corrupt-whisper-files.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-fill.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-diff.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-update.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/update-storage-times.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-create.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-fetch.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-set-aggregation-method.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-set-xfilesfactor.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/rrd2whisper.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-merge.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-resize.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-info.py to 755
    virtualbox-iso: changing mode of /usr/local/bin/whisper-auto-update.py to 755
    virtualbox-iso: Successfully installed whisper
    virtualbox-iso: Cleaning up...
    virtualbox-iso: Downloading/unpacking carbon
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/carbon/setup.py) egg_info for package carbon
    virtualbox-iso: ################################################################################
    virtualbox-iso:
    virtualbox-iso: Carbon's default installation prefix is "/opt/graphite".
    virtualbox-iso:
    virtualbox-iso: To install Carbon in the Python's default location run:
    virtualbox-iso: $ GRAPHITE_NO_PREFIX=True python setup.py install
    virtualbox-iso:
    virtualbox-iso: ################################################################################
    virtualbox-iso:
    virtualbox-iso: package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
    virtualbox-iso: warning: no files found matching '*' under directory 'conf/'
    virtualbox-iso: warning: no files found matching '*' under directory 'distro/'
    virtualbox-iso: warning: no previously-included files found matching 'conf/*.conf'
    virtualbox-iso: Downloading/unpacking Twisted (from carbon)
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/Twisted/setup.py) egg_info for package Twisted
    virtualbox-iso: no previously-included directories found matching '.travis'
    virtualbox-iso: no previously-included directories found matching 'tests'
    virtualbox-iso: warning: no previously-included files found matching 'examplesetup.py'
    virtualbox-iso: no previously-included directories found matching 'src/exampleproj'
    virtualbox-iso: no previously-included directories found matching 'src/incremental/newsfragments'
    virtualbox-iso:
    virtualbox-iso: Installed /tmp/pip_build_root/Twisted/incremental-17.5.0-py2.7.egg
    virtualbox-iso:
    virtualbox-iso: warning: no previously-included files matching '*.misc' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.bugfix' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.doc' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.feature' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.removal' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'NEWS' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'README' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'newsfragments' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files found matching 'src/twisted/topfiles/CREDITS'
    virtualbox-iso: warning: no previously-included files found matching 'src/twisted/topfiles/ChangeLog.Old'
    virtualbox-iso: warning: no previously-included files found matching 'pyproject.toml'
    virtualbox-iso: warning: no previously-included files found matching 'codecov.yml'
    virtualbox-iso: warning: no previously-included files found matching 'appveyor.yml'
    virtualbox-iso: warning: no previously-included files found matching '.circleci'
    virtualbox-iso: warning: no previously-included files matching '*' found under directory '.circleci'
    virtualbox-iso: no previously-included directories found matching 'bin'
    virtualbox-iso: no previously-included directories found matching 'admin'
    virtualbox-iso: no previously-included directories found matching '.travis'
    virtualbox-iso: no previously-included directories found matching '.github'
    virtualbox-iso: warning: no previously-included files found matching 'docs/historic/2003'
    virtualbox-iso: warning: no previously-included files matching '*' found under directory 'docs/historic/2003'
    virtualbox-iso: Downloading/unpacking txAMQP (from carbon)
    virtualbox-iso: Downloading txAMQP-0.8.2.tar.gz
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/txAMQP/setup.py) egg_info for package txAMQP
    virtualbox-iso:
    virtualbox-iso: Downloading/unpacking cachetools (from carbon)
    virtualbox-iso: Downloading cachetools-3.1.0-py2.py3-none-any.whl
    virtualbox-iso: Requirement already satisfied (use --upgrade to upgrade): urllib3 in /usr/lib/python2.7/dist-packages (from carbon)
    virtualbox-iso: Downloading/unpacking zope.interface>=4.4.2 (from Twisted->carbon)
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/zope.interface/setup.py) egg_info for package zope.interface
    virtualbox-iso: /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
    virtualbox-iso: warnings.warn(msg)
    virtualbox-iso:
    virtualbox-iso: warning: no previously-included files matching '*.dll' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.pyc' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.pyo' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.so' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
    virtualbox-iso: no previously-included directories found matching 'docs/_build'
    virtualbox-iso: Downloading/unpacking constantly>=15.1 (from Twisted->carbon)
    virtualbox-iso: Downloading constantly-15.1.0-py2.py3-none-any.whl
    virtualbox-iso: Downloading/unpacking incremental>=16.10.1 (from Twisted->carbon)
    virtualbox-iso: Downloading incremental-17.5.0-py2.py3-none-any.whl
    virtualbox-iso: Downloading/unpacking Automat>=0.3.0 (from Twisted->carbon)
    virtualbox-iso: Downloading Automat-0.7.0-py2.py3-none-any.whl
    virtualbox-iso: Downloading/unpacking hyperlink>=17.1.1 (from Twisted->carbon)
    virtualbox-iso: Downloading hyperlink-18.0.0-py2.py3-none-any.whl
    virtualbox-iso: Downloading/unpacking PyHamcrest>=1.9.0 (from Twisted->carbon)
    virtualbox-iso: Downloading/unpacking attrs>=17.4.0 (from Twisted->carbon)
    virtualbox-iso: Downloading attrs-18.2.0-py2.py3-none-any.whl
    virtualbox-iso: Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from txAMQP->carbon)
    virtualbox-iso: Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from zope.interface>=4.4.2->Twisted->carbon)
    virtualbox-iso: Downloading/unpacking idna>=2.5 (from hyperlink>=17.1.1->Twisted->carbon)
    virtualbox-iso: Installing collected packages: carbon, Twisted, txAMQP, cachetools, zope.interface, constantly, incremental, Automat, hyperlink, PyHamcrest, attrs, idna
    virtualbox-iso: Running setup.py install for carbon
    virtualbox-iso: ################################################################################
    virtualbox-iso:
    virtualbox-iso: Carbon's default installation prefix is "/opt/graphite".
    virtualbox-iso:
    virtualbox-iso: To install Carbon in the Python's default location run:
    virtualbox-iso: $ GRAPHITE_NO_PREFIX=True python setup.py install
    virtualbox-iso:
    virtualbox-iso: ################################################################################
    virtualbox-iso: package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
    virtualbox-iso: changing mode of build/scripts-2.7/carbon-cache.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/carbon-client.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/validate-storage-schemas.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/carbon-relay.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/carbon-aggregator.py from 644 to 755
    virtualbox-iso: changing mode of build/scripts-2.7/carbon-aggregator-cache.py from 644 to 755
    virtualbox-iso:
    virtualbox-iso: warning: no files found matching '*' under directory 'conf/'
    virtualbox-iso: warning: no files found matching '*' under directory 'distro/'
    virtualbox-iso: warning: no previously-included files found matching 'conf/*.conf'
    virtualbox-iso: changing mode of /opt/graphite/bin/carbon-cache.py to 755
    virtualbox-iso: changing mode of /opt/graphite/bin/carbon-client.py to 755
    virtualbox-iso: changing mode of /opt/graphite/bin/validate-storage-schemas.py to 755
    virtualbox-iso: changing mode of /opt/graphite/bin/carbon-relay.py to 755
    virtualbox-iso: changing mode of /opt/graphite/bin/carbon-aggregator.py to 755
    virtualbox-iso: changing mode of /opt/graphite/bin/carbon-aggregator-cache.py to 755
    virtualbox-iso: Running setup.py install for Twisted
    virtualbox-iso:
    virtualbox-iso: warning: no previously-included files matching '*.misc' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.bugfix' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.doc' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.feature' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching '*.removal' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'NEWS' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'README' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files matching 'newsfragments' found under directory 'src/twisted'
    virtualbox-iso: warning: no previously-included files found matching 'src/twisted/topfiles/CREDITS'
    virtualbox-iso: warning: no previously-included files found matching 'src/twisted/topfiles/ChangeLog.Old'
    virtualbox-iso: warning: no previously-included files found matching 'pyproject.toml'
    virtualbox-iso: warning: no previously-included files found matching 'codecov.yml'
    virtualbox-iso: warning: no previously-included files found matching 'appveyor.yml'
    virtualbox-iso: warning: no previously-included files found matching '.circleci'
    virtualbox-iso: warning: no previously-included files matching '*' found under directory '.circleci'
    virtualbox-iso: no previously-included directories found matching 'bin'
    virtualbox-iso: no previously-included directories found matching 'admin'
    virtualbox-iso: no previously-included directories found matching '.travis'
    virtualbox-iso: no previously-included directories found matching '.github'
    virtualbox-iso: warning: no previously-included files found matching 'docs/historic/2003'
    virtualbox-iso: warning: no previously-included files matching '*' found under directory 'docs/historic/2003'
    virtualbox-iso: building 'twisted.test.raiser' extension
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/twisted/test/raiser.c -o build/temp.linux-x86_64-2.7/src/twisted/test/raiser.o
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/twisted/test/raiser.o -o build/lib.linux-x86_64-2.7/twisted/test/raiser.so
    virtualbox-iso: building 'twisted.python._sendmsg' extension
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/twisted/python/_sendmsg.c -o build/temp.linux-x86_64-2.7/src/twisted/python/_sendmsg.o
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/twisted/python/_sendmsg.o -o build/lib.linux-x86_64-2.7/twisted/python/_sendmsg.so
    virtualbox-iso: Installing conch script to /usr/local/bin
    virtualbox-iso: Installing ckeygen script to /usr/local/bin
    virtualbox-iso: Installing twist script to /usr/local/bin
    virtualbox-iso: Installing trial script to /usr/local/bin
    virtualbox-iso: Installing pyhtmlizer script to /usr/local/bin
    virtualbox-iso: Installing mailmail script to /usr/local/bin
    virtualbox-iso: Installing tkconch script to /usr/local/bin
    virtualbox-iso: Installing twistd script to /usr/local/bin
    virtualbox-iso: Installing cftp script to /usr/local/bin
    virtualbox-iso: Running setup.py install for txAMQP
    virtualbox-iso:
    virtualbox-iso: Running setup.py install for zope.interface
    virtualbox-iso: /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
    virtualbox-iso: warnings.warn(msg)
    virtualbox-iso:
    virtualbox-iso: warning: no previously-included files matching '*.dll' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.pyc' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.pyo' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching '*.so' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
    virtualbox-iso: warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
    virtualbox-iso: no previously-included directories found matching 'docs/_build'
    virtualbox-iso: building 'zope.interface._zope_interface_coptimizations' extension
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/zope/interface/_zope_interface_coptimizations.c -o build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o
    virtualbox-iso: x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o -o build/lib.linux-x86_64-2.7/zope/interface/_zope_interface_coptimizations.so
    virtualbox-iso: Skipping installation of /usr/local/lib/python2.7/dist-packages/zope/__init__.py (namespace package)
    virtualbox-iso: Installing /usr/local/lib/python2.7/dist-packages/zope.interface-4.6.0-nspkg.pth
    virtualbox-iso: Successfully installed carbon Twisted txAMQP cachetools zope.interface constantly incremental Automat hyperlink PyHamcrest attrs idna
    virtualbox-iso: Cleaning up...
    virtualbox-iso: Downloading/unpacking graphite-web
    virtualbox-iso: Running setup.py (path:/tmp/pip_build_root/graphite-web/setup.py) egg_info for package graphite-web
    virtualbox-iso:
    virtualbox-iso: warning: no files found matching '*' under directory 'distro/'
    virtualbox-iso: warning: no files found matching '*.html' under directory 'webapp/graphite/'
    virtualbox-iso: warning: no files found matching '*' under directory 'webapp/content/'
    virtualbox-iso: warning: no previously-included files found matching 'webapp/graphite/local_settings.py'
    virtualbox-iso: warning: no previously-included files found matching 'conf/*.conf'
    virtualbox-iso: Downloading/unpacking Django>=1.8,<2.1 (from graphite-web)
    virtualbox-iso: Cleaning up...
    virtualbox-iso: Exception:
    virtualbox-iso: Traceback (most recent call last):
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    virtualbox-iso: status = self.run(options, args)
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    virtualbox-iso: requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    virtualbox-iso: do_download,
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    virtualbox-iso: self.session,
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    virtualbox-iso: unpack_file(temp_location, location, content_type, link)
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    virtualbox-iso: untar_file(filename, location)
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/pip/util.py", line 574, in untar_file
    virtualbox-iso: path = os.path.join(location, fn)
    virtualbox-iso: File "/usr/lib/python2.7/posixpath.py", line 80, in join
    virtualbox-iso: path += '/' + b
    virtualbox-iso: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 47: ordinal not in range(128)
    virtualbox-iso:
    virtualbox-iso: Storing debug log for failure in /home/vagrant/.pip/pip.log
    virtualbox-iso: cp: cannot stat ‘examples/graphite.wsgi.example’: No such file or directory
    virtualbox-iso: cp: cannot stat ‘/opt/graphite/webapp/graphite/local_settings.py.example’: No such file or directory
    virtualbox-iso: python: can't open file '/opt/graphite/webapp/graphite/manage.py': [Errno 2] No such file or directory
    virtualbox-iso: chown: cannot access ‘/opt/graphite/webapp/’: No such file or directory
    virtualbox-iso: Traceback (most recent call last):
    virtualbox-iso: Starting carbon-cache (instance a)
    virtualbox-iso: File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    virtualbox-iso: run_twistd_plugin(__file__)
    virtualbox-iso: File "/opt/graphite/lib/carbon/util.py", line 140, in run_twistd_plugin
    virtualbox-iso: runApp(config)
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    virtualbox-iso: runner.run()
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 381, in run
    virtualbox-iso: self.application = self.createOrGetApplication()
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 448, in createOrGetApplication
    virtualbox-iso: ser = plg.makeService(self.config.subOptions)
    virtualbox-iso: File "/opt/graphite/lib/twisted/plugins/carbon_cache_plugin.py", line 20, in makeService
    virtualbox-iso: from carbon import service
    virtualbox-iso: File "/opt/graphite/lib/carbon/service.py", line 36, in <module>
    virtualbox-iso: import carbon.amqp_listener
    virtualbox-iso: File "/opt/graphite/lib/carbon/amqp_listener.py", line 46, in <module>
    virtualbox-iso: from txamqp.protocol import AMQClient
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/txamqp/protocol.py", line 15, in <module>
    virtualbox-iso: from txamqp.connection import Header, Frame, Method, Body, Heartbeat
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/txamqp/connection.py", line 60, in <module>
    virtualbox-iso: class Payload(with_metaclass(PayloadMeta, object)):
    virtualbox-iso: File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    virtualbox-iso: return meta("NewBase", bases, {})
    virtualbox-iso: File "/usr/local/lib/python2.7/dist-packages/txamqp/connection.py", line 52, in __new__
    virtualbox-iso: raise TypeError("%s must define %s" % (name, req))
    virtualbox-iso: TypeError: NewBase must define encode
    virtualbox-iso: * Restarting app server(s) uwsgi
    virtualbox-iso: ...done.
```
